CREATE TABLE EMPLOYEES01(
	EMP_NO INT(11) NOT NULL
	, BIRTH_DATE DATE NOT NULL
	, FIRST_NAME VARCHAR(14) NOT NULL
	, LAST_NAME VARCHAR(16) NOT NULL
	, GENDER ENUM('M','F') NOT NULL
	, HIRE_DATE DATE NOT NULL
	, CONSTRAINT PK_EMPLOYEES01_EMP_NO PRIMARY KEY(EMP_NO)
);


CREATE TABLE salaries01(
	EMP_NO INT(11) NOT NULL
	, SALARY INT(11) NOT NULL
	, FROM_DATE DATE NOT NULL
	, TO_DATE DATE NOT NULL
	, CONSTRAINT PK_EMPLOYEES01_SALARIES01
		PRIMARY KEY(EMP_NO, FROM_DATE)
	, CONSTRAINT FK_EMPLOYEES01_SALARIES01	
		FOREIGN KEY (EMP_NO) REFERENCES employees01(EMP_NO)	
);
CREATE INDEX EMP_NO ON salaries01(EMP_NO);





CREATE TABLE titles01(
	EMP_NO INT(11) NOT NULL
	, TITLE VARCHAR(50) NOT NULL
	, FROM_DATE DATE NOT NULL
	, TO_DATE DATE
	, CONSTRAINT PK_EMPLOYEES01_TITLES01
		PRIMARY KEY(EMP_NO, TITLE, FROM_DATE)
	, CONSTRAINT FK_EMPLOYEES01_TITLES01
		FOREIGN KEY(EMP_NO) REFERENCES employees01(EMP_NO)
);
CREATE INDEX EMP_NO ON titles01(EMP_NO);

SHOW FULL COLUMNS FROM titles01;
