CREATE TABLE STUDENT_INFO (
	STU_NO INT(10) NOT NULL
	, SUT_BIRTH_DATE DATE NOT NULL
	, STU_NAME VARCHAR(30) NOT NULL
	, STU_ADDR VARCHAR(100) NOT NULL
	, STU_GENDER ENUM('F','M') NOT NULL
	, STU_CALL_NO INT(11) NOT NULL 
												-- CHAR 보통 사용! 자릿수 정해져 있기 때문 / INT 넣으면 앞에 0 없어짐....!
	, STU_IN_DATE DATE NOT NULL
	, STU_OUT_DATE DATE NULL
	, STU_STATE VARCHAR(2) NOT NULL
	, CONSTRAINT PK_STUDENT_INFO_STU_NO PRIMARY KEY(STU_NO)
);

CREATE TABLE TEST_INFO (
	STU_NO INT(10) NOT NULL
	, SUBJ_NO VARCHAR(10) NOT NULL
	, SUBJ_RESULT INT(3) NOT NULL
	, SUBJ_RANK INT(3) NOT NULL
	, SUBJ_END_DATE DATE NOT NULL
	, CONSTRAINT PK_TEST_INFO_STU_NO_SUBJ_NO PRIMARY KEY(STU_NO, SUBJ_NO)
);

CREATE TABLE PROF_INFO(
	PROF_NO INT(10) NOT NULL
	, PROF_NAME VARCHAR(30) NOT NULL
	, PROF_BIRTH_DATE DATE NOT NULL
	, PROF_DEGREE VARCHAR(30) NOT NULL
	, PROF_EMAIL VARCHAR(30) NOT NULL
	, PROF_TITLE VARCHAR(10) NOT NULL
	, PFOR_GENDER ENUM('F', 'M') NOT NULL
	, PROF_HIRE_DATE DATE NOT NULL
	, PROF_ROMM_NO INT(5) NOT NULL
	, CONSTRAINT PK_PROF_INFO_PROF_NO PRIMARY KEY(PROF_NO)
);

CREATE TABLE SUBJECT_INFO(
	SUBJ_NO VARCHAR(10) NOT NULL
	, SUBJ_NAME VARCHAR(100) NOT NULL
	, SUBJ_LIMIT INT(3) NOT NULL
	, SUBJ_SEMESTER ENUM('0','1', '2','3') NOT NULL
	, CLASSROOM_NO INT(5) NOT NULL
	, CLASS_START_TIME INT(2) NOT NULL
	, CLASS_END_TIME INT(2) NOT NULL
	, SUBJ_MUST ENUM('Y', 'N') NOT NULL
	, BOOK_NO VARCHAR(10)
	, PROF_NO INT(10)
	, CONSTRAINT PK_SUBJECT_INFO PRIMARY KEY(SUBJ_NO, BOOK_NO, PROF_NO)
);


CREATE TABLE CLASSBOOK_INFO(
	BOOK_NO VARCHAR(10)
	, BOOK_NAME VARCHAR(100) NOT NULL
	, CONSTRAINT PK_CLASSBOOK_INFO PRIMARY KEY(BOOK_NO)
);


	